configserver: true
bus: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eurekaserver.credentials.uri:http://127.0.0.1:8761}/eureka/
ribbon:
  eureka:
    enabled: true

---

spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80