configserver: true
bus: true

eureka:    
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8680/eureka
  instance:
    leaseRenewalIntervalInSeconds: 10
ribbon:
  eureka:
    enabled: true

---

spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80