spring:
  profiles:
    active: development

---

spring:
  profiles: development
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eurekaserver/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
ribbon:
  eureka:
    enabled: false
	
---

spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver-infogain.rhcloud.com/eurekaserver/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: ${vcap.application.uris[0]}    
    nonSecurePort: 80
ribbon:
  eureka:
    enabled: true