---
spring:
  profiles: cloud
  cloud:
    config:
      uri: ${vcap.services.${PREFIX:}ige-config-server.credentials.uri:http://${PREFIX:}${ige-config-server.${application.domain:cfapps.io}}}
application:
  domain: ${APPLICATION_DOMAIN:cfapps.io}
endpoints:
  restart: enabled
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}ige-eureka-server.credentials.uri:http://${PREFIX:}ige-eureka-server.${application.domain:cfapps.io}}/ige-eureka-server/  