configserver: true
bus: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8084}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.ige-service-registry.credentials.uri:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: cloud
  data:
    mongodb:
      uri: ${vcap.services.${PREFIX:}mongodb.credentials.uri:mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/productsApi}
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80