spring:
  profiles:
    active: development

---

spring:
  profiles: development
server:
  port: 8761
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: cloud
  cloud:
    config:
      discovery:
        enabled: true
server:
  port: 8761
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaserver-infogain.rhcloud.com/eureka/