spring:
  profiles:
    active: development

---

spring:
  profiles: development
server:
  port: 9005
  data:
    mongodb:
      uri: ${vcap.services.${PREFIX:}mongodb.credentials.uri}
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eurekaserver/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: false

---

spring:
  profiles: cloud
server:
  port: 9005
  data:
    mongodb:
      uri: ${vcap.services.${PREFIX:}mongodb.credentials.uri}
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver-infogain.rhcloud.com/eurekaserver/eureka/
  instance:
    hostname: product-infogain.rhcloud.com
    nonSecurePort: 80
ribbon:
  eureka:
    enabled: true